java.lang.AssertionError: +drawable in org.jetbrains.android.dom.resources.ResourceValue
Fix for user reported crash (b/15541233) which can occur if you enter an
invalid resource URL in the editor such as @+drawable/foo.

Change-Id: I8682172fca2f59631b08d9f2c38182328b2100d0
(cherry picked from commit dc3cf88f20e6d5df43287835d96b8ea961e8a7d6)