Now we suggest how to fix ClassNotFoundException and NoSuchMethodError thrown during project sync.
ClassNotFoundExceptions during project sync may happen because of:
1. Duplicated builder jars in Android Studio (this happens when users
   unzip a newer IDE installation on top of an old one)
2. Corrupt or out of date Gradle dependency cache
3. The state of the Gradle daemon performing the sync is corrupt

Issue #1 was already fixed (
https://android-review.googlesource.com/99790)

For #2 and #3 we offer quick-fix links that
- Re-download dependencies and sync project
- Stops all Gradle daemons (warning users that this will terminate
  any currently running builds) and sync project

For #3 we also suggest to close the IDE and kill all Java processes.

Fixes issue
https://code.google.com/p/android/issues/detail?id=73872

Change-Id: Ib634e3653f4614fc168a21caaaa6bee970bc8d99
(cherry picked from commit 63968896d496fefcbfa70c64601de7ab220211c6)